steps:
- name: gcr.io/cloud-builders/docker
  args:
  - build
  - -t
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/kube/${REPO_NAME}:${_ENV_IMAGE_TAG}-${COMMIT_SHA}-${BUILD_ID}'
  - -t
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/kube/${REPO_NAME}:${_ENV_IMAGE_TAG}'
  - .
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/kube/${REPO_NAME}:${_ENV_IMAGE_TAG}-${COMMIT_SHA}-${BUILD_ID}'
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/kube/${REPO_NAME}:${_ENV_IMAGE_TAG}'
substitutions:
  _ENV_IMAGE_TAG: test